### PR TITLE
Update deprecated str_replace() call

### LINKED ISSUE #440: config-get on PHP 8.1: Deprecated str_replace(): Passing null to parameter #3
- moosh version: 1.11
- moodle version: 402
    - database: MySQL 8.0.33-0ubuntu0.22.04.2
- php version: 8.1.2-1ubuntu2.11
- operating system: Ubuntu 22.04.2 LTS

### Actual behaviour

A PHP deprecation warning (once on stderr and once on stdout)
```bash
ahoyt@mdl2:/opt/moodle$ sudo -u www-data moosh config-get core siteadmins
PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /usr/share/moosh/Moosh/MooshCommand.php on line 254

Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /usr/share/moosh/Moosh/MooshCommand.php on line 254
2
```

Also, seems like stderr ends up in stdout, so users can only suppress one of the warnings:
```
$ sudo -u www-data moosh config-get core siteadmins 2>/dev/null # Still shows one of the warnings
```
### Expected behaviour

No deprecation warnings

### Steps to reproduce

Each of these reproduces it for me:
```
sudo -u www-data moosh config-get core siteadmins
sudo -u www-data moosh config-get core
sudo -u www-data moosh user-list --id "username IN ('ahoyt')"
```

### PR DESCRIPTION
**Pull request by Zyten**
Closes #440

### CODE REVIEW

**Comment by ansonhoyt** [comment]
I'm not good with PHP, but your solution seems reasonable.

This looks like an instance of [PHP 8.1: Passing null to non-nullable internal function parameters is deprecated](https://php.watch/versions/8.1/internal-func-non-nullable-null-deprecation), and `""` seems like the right thing to use for strings.

Looks like [str_replace()](https://www.php.net/manual/en/function.str-replace.php) accepts `string|array`, and your solution handles converting both `null` and `array()` to `""`.

If `$v` is never an array, then casting might be clearer than a ternary operator: `(string)$v`

👍

**Comment by tmuras** [comment]
Thank you very much for the PR. I've got it sorted in another commit, so it should not be needed - but it is much appreciated, keep sending PRs :)

**Comment by ansonhoyt** [comment]
@tmuras Thanks for the fix! I was looking to test it out, but it looks like the `1.12` release only shows up in your [Ubuntu PPA](https://launchpad.net/~zabuch/+archive/ubuntu/ppa) for `trusty`. I'm using `jammy` with their PHP 8.1 to reproduce this issue.

**Comment by koenr** [comment]
I'm on focal and also get Moosh 1.11 through the ppa, showing this problem with PHP 8.2.12

**Pull request closed without merging**
