### PR TITLE
New plugin - Filter Set (Turn site-wide filers on/off)

### PR DESCRIPTION
**Pull request by nadavkav**
Again, life calls for a new plugin...
As I needed to set several filters system-wide on several system, I added a new plugin called "filter-set" to help me set (turn ON) those system-wide filters.

Please review and see if you can add it :-)

### CODE REVIEW

**Comment by tmuras** [comment]
Hi and thanks for sharing!

It looks good - I just think I'll move it from Generic namespace (which is for all Moodles, no matter version) to version-specific one. lib/classes/plugin_manager.php  was added in Moodle 2.6, so that's probably the lowest version where this will work.

**Comment by nadavkav** [comment]
Great! (Fine with me, move it where ever it seems best)

**Comment by nadavkav** [comment]
Ping :-)

**Comment by tmuras** [comment]
I'm back in business :)

**Comment by nadavkav** [comment]
Sweet :-) Thanks!

**Pull request merged**
